# Generated by Django 3.2.5 on 2021-08-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('h1', models.CharField(max_length=500)),
                ('p1', models.CharField(max_length=5000)),
                ('h2', models.CharField(max_length=500)),
                ('p2', models.CharField(max_length=5000)),
                ('h3', models.CharField(max_length=500)),
                ('p3', models.CharField(max_length=5000)),
                ('publishedAt', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
