# Generated by Django 3.2.5 on 2021-08-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210807_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
