# Generated by Django 3.2.5 on 2021-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210807_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.IntegerField(default=0),
        ),
    ]
