# Generated by Django 3.2.5 on 2021-08-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderedDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Dispatched', 'Dispatched'), ('On The Way', 'On The Way'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=80),
        ),
    ]
